blank_issues_enabled: false
contact_links:
  - name: Slimefun Addon Community Discord Server (for suggestions and questions)
    url: https://discord.gg/SqD3gg5SAU
    about: Please ask or give suggestions here in `#bump` channel.
  - name: 没有 Github 账号? 不会使用 Github?
    url: https://ybw0014.net/go/sf-qgroup
    about: 点击右侧按钮加入QQ群进行反馈
